### ISSUE TITLE
最初に鳴らす音について

### ISSUE THREAD

**Issue by CURRY-AND-RICE** [yudaisugiyama/Noimu#7]
決定したらそのwavをmusic.wavとして配置し、コード内のDQN.latest_promptの初期値をそのプロンプトに設定する

**Comment by yudaisugiyama** [comment]
アンケート調査で決めるのもアリ。時間がなければメンバーの5人のアンケートでも良いのでは。

**Comment by yudaisugiyama** [comment]
↑ハッカソンのslackに共有しても何人か返信くれそうだけども?

**Comment by CURRY-AND-RICE** [comment]
説明するの大変かも

**Comment by yudaisugiyama** [comment]
了解、5人のアンケートにしましょ

**Comment by yudaisugiyama** [comment]
最初の音を選択する実装終わったらcloseしてください🙇‍♂️

**Comment by CURRY-AND-RICE** [comment]
オーケー、明日中に音楽渡す

**Comment by CURRY-AND-RICE** [comment]
devブランチでのコミットにて適用
